version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: cron
      cronjob: 0 17 5 * *
    groups:
      github-actions:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: cron
      cronjob: 0 17 5 * *
    groups:
      npm-dependencies:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
